//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_SIGO_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItensOrdem
    {
        public int ID { get; set; }
        public string Tipo { get; set; }
        public string Garantia { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string Obs { get; set; }
        public string Defeito { get; set; }
        public Nullable<int> IDProduto { get; set; }
        public Nullable<int> IDServico { get; set; }
        public Nullable<int> IDOrdemDeServico { get; set; }
    
        public virtual OrdemDeServico OrdemDeServico { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual Servico Servico { get; set; }
    }
}
