//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_SIGO_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Projeto_SIGOEntities : DbContext
    {
        public Projeto_SIGOEntities()
            : base("name=Projeto_SIGOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarroAtual> CarroAtual { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Endereco> Endereco { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Fornecedor> Fornecedor { get; set; }
        public virtual DbSet<ItensOrdem> ItensOrdem { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<OrdemDeServico> OrdemDeServico { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<Servico> Servico { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<mensagem> mensagem { get; set; }
    }
}
